BugTracker2/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BugTracker2.Models
{
    public class Ticket
    {
        public Ticket()
        {
            this.Attachments = new HashSet<TicketAttachment>();
            this.History = new HashSet<TicketHistory>();
            this.Notifications = new HashSet<TicketNotification>();
        }
        public int Id { get; set; }
        [Display(Name = "Project")]
        public int ProjectId { get; set; }
        [Display(Name = "Assigned to")]
        public string AssignedUserId { get; set; }
        [Display(Name = "Created by")]
        public string CreatedUserId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        [Display(Name = "Type")]
        public int? TypeId { get; set; }
        [Display(Name ="Status")]
        public int? StatusId { get; set; }
        [Display(Name = "Priority Level")]
        public int? PriorityId { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? Updated { get; set; }

        public virtual ApplicationUser CreatedUser { get; set; }
        public virtual Project Project { get; set; }
        public virtual ApplicationUser AssignedUser { get; set; }
        public virtual TicketType Type { get; set; }
        public virtual TicketStatus Status { get; set; }
        public virtual TicketPriority Priority { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<TicketAttachment> Attachments { get; set; }
        public virtual ICollection<TicketHistory> History { get; set; }
        public virtual ICollection<TicketNotification> Notifications { get; set; }
    }
}

BugTracker2/Models/TicketType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BugTracker2.Models
{
    public class TicketType
    {
        public TicketType()
        {
            this.Ticket = new HashSet<Ticket>();
        }
        public int Id { get; set; }
        public int TicketId { get; set; }
        public string Type { get; set; }

        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}

BugTracker2/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugTracker2.Models;
using Microsoft.AspNet.Identity;

namespace BugTracker2
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.User).Include(c => c.Ticket);
            return View(comments.ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "AssignedUserId");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "Id,TicketId,UserId,Body,Created,Updated,UpdatedReason")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.Created = DateTimeOffset.Now;
                comment.UserId = User.Identity.GetUserId();
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Details", "Tickets", new { id = comment.TicketId });
            }

            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "AssignedUserId", comment.TicketId);
            return View(comment);
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "AssignedUserId", comment.TicketId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TicketId,UserId,Body,Created,Updated,UpdatedReason")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "AssignedUserId", comment.TicketId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BugTracker2/Controllers/TicketAttachmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugTracker2.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace BugTracker2
{
    public class TicketAttachmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TicketAttachments
        public ActionResult Index()
        {
            return View(db.Attachments.ToList());
        }

        // GET: TicketAttachments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketAttachment ticketAttachment = db.Attachments.Find(id);
            if (ticketAttachment == null)
            {
                return HttpNotFound();
            }
            return View(ticketAttachment);
        }

        //// GET: TicketAttachments/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: TicketAttachments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "TicketId,Body")] TicketAttachment ticketAttachment, HttpPostedFileBase image)
        {
            

            if (ModelState.IsValid)
            {
                ticketAttachment.CreatedDate = DateTimeOffset.Now;
                ticketAttachment.UserId = User.Identity.GetUserId();

                if (image != null && image.ContentLength > 0)
                        {                                                       
                            //relative server path
                            var filePath = "/Uploads/";
                            // path on physical drive on server
                            var absPath = Server.MapPath("~" + filePath);
                            // media url for relative path
                            ticketAttachment.MediaURL = filePath + image.FileName;
                            //save image
                            image.SaveAs(Path.Combine(absPath, image.FileName));

                            //check the file name to make sure its an image
                            var ext = Path.GetExtension(image.FileName).ToLower();
                            if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".bmp")
                            ModelState.AddModelError("image", "Invalid Format.");
                        }
                db.Attachments.Add(ticketAttachment);
                db.SaveChanges();
                return RedirectToAction("Details", "Tickets", new { id = ticketAttachment.TicketId });
            }

            return View();
        }

        // GET: TicketAttachments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketAttachment ticketAttachment = db.Attachments.Find(id);
            if (ticketAttachment == null)
            {
                return HttpNotFound();
            }
            return View(ticketAttachment);
        }

        // POST: TicketAttachments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TicketId,Body,MediaURL")] TicketAttachment ticketAttachment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ticketAttachment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ticketAttachment);
        }

        // GET: TicketAttachments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketAttachment ticketAttachment = db.Attachments.Find(id);
            if (ticketAttachment == null)
            {
                return HttpNotFound();
            }
            return View(ticketAttachment);
        }

        // POST: TicketAttachments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TicketAttachment ticketAttachment = db.Attachments.Find(id);
            db.Attachments.Remove(ticketAttachment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BugTracker2/Views/Tickets/Create.cshtml
@model BugTracker2.Models.Ticket

@{
    ViewBag.Title = "Create";
}

<h2>Create new Ticket</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ticket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProjectId, "List of Projects", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.StatusId, "Ticket Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.PriorityId, "Ticket Priority", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PriorityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PriorityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeId, "Ticket Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Body, 4, 50, new { @class = "form-control", style = "max-width:80%" })
                    @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })

                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BugTracker2/Views/Tickets/Delete.cshtml
@model BugTracker2.Models.Ticket

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AssignedUser.Fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignedUser.Fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedUser.Fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUser.Fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BugTracker2/Views/Tickets/Details.cshtml
@model BugTracker2.Models.Ticket

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AssignedUser.Fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignedUser.Fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedUser.Fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUser.Fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

    </dl>
</div>

<div>
    @using (Html.BeginForm("Create", "Comments", FormMethod.Post))
    {
        <input type="hidden" name="TicketId" value="@Model.Id" />
        <textarea name="Body"></textarea>
            <input type="submit" />
    }
</div>
@foreach (var comment in Model.Comments)
{
    <ul>
        <li>Posted by @comment.User.Fname at @comment.Created</li>
        <li>@comment.Body</li>
    </ul>
    <p>
        @Html.ActionLink("Edit", "Edit", "Comments", new { id = comment.Id }, null) |
        @Html.ActionLink("Delete", "Delete", "Comments", new { id = comment.Id }, null)
    </p>
}
<div>
    @using (Html.BeginForm("Create", "TicketAttachments", FormMethod.Post, new { enctype = "Multipart/form-data" }))
    {
        <input type="hidden" id="TicketId" name="TicketId" value="@Model.Id" />
        <input name="image" type="file" class="form-control" id="image" />
        <textarea id="Body" name="Body"></textarea>
        <input type="submit" />
    }
    @foreach (var ticketAttachment in Model.Attachments)
    {
        <div>Posted by @ticketAttachment.User.Fname @ticketAttachment.Body</div>
        <div>@ticketAttachment.MediaURL</div>
        <img src="@ticketAttachment.MediaURL" alt="Attachment Photo" style="max-width:150px" />

        <p>
            @Html.ActionLink("Delete", "Delete", "TicketAttachments", new { id = ticketAttachment.Id }, null)
        </p>
    }
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@*@if (Model.History Count > 0)
{
    <h4><u>Ticket History</u></h4>
    foreach (var history in Model.History)
    {
        if (history.Property == "AssignedToUserId" || history.Property == "Body" || history.Property == "TicketTypeId" || history.Property == "TicketStatusId")
        {
            <div class="panel panel-default">
                <div class="panel-heading">
                    The <b>@history.PropertyDisplay</b> was <b>changed from</b> @(history.OldValueDisplay ?? "unset") <b>to</b> @(history.NewValueDisplay ?? "unset"), <b>on</b> @history.Modified.ToString("g")
                </div>
            </div>
        }
        else if (history.Property == "Notifications")
        {
            <div class="panel panel-default">
                <div class="panel-heading">
                    A <b>@history.PropertyDisplay</b> was <b>sent</b> to @Model.AssignedUser.Email <b>on</b> @history.Modified.ToString("g").
                </div>
            </div>
        }
    }
    <br />
    <br />
}*@

BugTracker2/Views/Tickets/Edit.cshtml
@model BugTracker2.Models.Ticket

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CreatedUserId)<!--include the 'CreatedUserId' field in the html form as a hidden field and it will bind to the submitted model-->
    @Html.HiddenFor(model => model.Created)<!--Include the 'Created' field also to persist it as well on submit-->
    <div class="form-horizontal">
        <h4>Ticket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (ViewContext.HttpContext.User.IsInRole("Project Manager"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.AssignedUserId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("AssignedUserId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AssignedUserId, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        @if (ViewContext.HttpContext.User.IsInRole("Project Manager"))
        {
        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.PriorityId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PriorityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PriorityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, 4, 50, new { @class = "form-control", style = "max-width:80%" })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BugTracker2/Views/Tickets/Index.cshtml
@model IEnumerable<BugTracker2.Models.Ticket>

@{
    ViewBag.Title = "Index";
}

<h2>List of Current Tickets</h2>

<p>
@if (ViewContext.HttpContext.User.IsInRole("Submitter"))
{ 
    @Html.ActionLink("Create New", "Create")
}
</p>
    <table id="mytable" class="table">
        <thead>
            <tr>
                <th>Assigned to</th>
                <th>Created by</th>
                <th>Project</th>
                <th>Title</th>
                <th>Body</th>
                <th>Type</th>
                <th>Status</th>
                <th>Priority Level</th>
                <th>Created Date</th>
                <th>Updated Date</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
           

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AssignedUser.Fname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedUser.Fname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Project.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Body)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Priority.Priority)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Created)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Updated)
                    </td>
                    
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @if (ViewContext.HttpContext.User.IsInRole("Admin"))
                    {
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    }
                    </td>
                </tr>
            }
        </tbody>
    </table>
@section cssStyle {
    @Styles.Render("~/Content/DataTables/css/jquery.dataTables.min.css")
}
@section scripts{
    <!-- DataTables -->
    @Scripts.Render("~/js/jquery.dataTables.min.js")
    <script src="~/Scripts/Chris.BugTracker2.js"></script>
}